creation_rules:
  - path_regex: secrets/local\.enc\.yaml$
    age: >-
      age1REPLACE_WITH_YOUR_LOCAL_AGE_PUBLIC_KEY

  - path_regex: secrets/vps\.enc\.yaml$
    age: >-
      age1REPLACE_WITH_YOUR_VPS_AGE_PUBLIC_KEY
