apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  template:
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: loki-data
