apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-unified-mcp-bff
  namespace: bff
spec:
  replicas: 0
  selector:
    matchLabels:
      app: github-unified-mcp-bff
  template:
    metadata:
      labels:
        app: github-unified-mcp-bff
    spec:
      serviceAccountName: platform-puller
      containers:
        - name: github-unified-mcp-bff
          image: ghcr.io/vinicius-ssantos/github-unified-mcp-bff:main
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: github-unified-mcp-bff-config
          env:
            - name: MCP_TOKEN
              value: local-dev-token
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            requests:
              cpu: 25m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 512Mi
