resources:
  - namespace.yaml
  - loki-config.yaml
  - loki-deployment.yaml
  - loki-service.yaml
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - alloy-rbac.yaml
  - alloy-config.yaml
  - alloy-deployment.yaml
  - grafana-datasources.yaml
  - grafana-alerting.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
