apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-puller
  namespace: mcp
imagePullSecrets:
  - name: ghcr-pull-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-puller
  namespace: bff
imagePullSecrets:
  - name: ghcr-pull-secret
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-puller
  namespace: vos
imagePullSecrets:
  - name: ghcr-pull-secret
